version: '3'
services:
  questionservice:
    container_name: questionservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_0/questionservice:latest
    profiles: ["dev", "prod"]
    build: ./questionservice
    ports:
      - "2500:2500" 

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_0/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    ports:
      - "3000:3000" 

  prometheus:
    image: prom/prometheus
    container_name: prometheus-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
