ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****

* *Microservicios:*
Enfoque arquitectónico donde el software está compuesto por pequeños servicios independientes. Lo hemos elegido por encima de MVC, por la facilidad a la hora de modificar una parte de la aplicación sin afectar al resto.

* *Docker:*
Este programa es utilizado para desplegar aquí la aplicación web y realizar las pruebas pertinentes. Facilidad a la hora de desplegar junto con una máquina virtual de Azure.

* *Wikidata:*
API impuesta al equipo de desarrollo como requisito del sistema, su proposito en la aplicación es la obtención de información de diferentes temas para un posterior desarrollo de preguntas.

* *Javascript:*
Lenguaje de programación interpretado, no tipado y facil de aprender y desarrollar. Utilizado para desarrollar todos los microservicios.

* *React:*
 Biblioteca de Javascript que se centra en el desarrollo de interfaces. Actualmente está en un momento de auge, por lo que aprender esta tecnologia sería bueno para el mercado laboral.
