ifndef::imagesdir[:imagesdir: ../images]

[[section-technical-risks]]
== Riesgos y Deudas Técnicas


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.

.Further Information

See https://docs.arc42.org/section-11/[Risks and Technical Debt] in the arc42 documentation.

****

=== Riesgos Técnicos

[cols="e,2e" options="header"]
|===
|Riesgo |Explicación

|*Abandono* 
|_Durante el desarrollo del proyecto cabe la posibilidad de que alguno de los miembros que conforman el equipo abandone este, provocando un serio problema el ritmo y carga
de trabajo de los demás compañeros._

|*Otras Asignaturas* 
|_Las demás asignaturas en la que están matriculados los miembros del equipo puede exigir una carga importante de trabajo por lo que provocar que el equipo no dedique el
suficiente tiempo al desarrollo de este proyecto._

|*Errores* 
|_Durante las pruebas de la aplicación pueden surgir errores que nos obliguen a realizar importantes cambios en esta. Esto puede provocar que el equipo invierta más horas de
las planeadas para solucionar este tipo de problemas._

|*Caída de Servicios* 
|_Nuestra aplicacion web puede verse comprometida a errores si alguno de los servicios utilizados, como por ejemplo Docker, parará de funcionar en algún momento.
Ya que los servicios no son creados por nosotros no podemos saber si estarán disponibles en todo momento por lo tanto  
esto podría bloquear la entrega de alguna de las funcionalidades del proyecto._

|*Problemas Software* 
|_No podemos asegurar que nuestra aplicación pueda ser utilizada por todos los usuarios ya que en ciertos casos dependerá del sistema operativo de cada usuario._

|*Problemas Hardware* 
|_Dependiendo desde el dispositivo que se acceda a la aplicación si este no cumple los requisitos, como la resolución de pantalla, puede ser que la aplicacion no se vea de la forma esperada._

|===



