global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "example-nodejs-app"
    static_configs:
      - targets: ["gatewayservice-wiq5a:8000","questionservice-wiq5a:8003","userservice-wiq5a:8001","authservice-wiq5a:8002"]