name: Build
on:
  push:
    branches:
      - master
      - develop
      - LaraFMz
      - Pablo-Arreglos
      - jota
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm --prefix userservice/authservice ci
    - run: npm --prefix userservice/userservice ci
    - run: npm --prefix gatewayservice ci
    - run: npm --prefix questionservice ci
    - run: npm --prefix webapp ci
    - run: npm --prefix userservice/authservice test -- --coverage
    - run: npm --prefix userservice/userservice test -- --coverage
    - run: npm --prefix gatewayservice test -- --coverage
    - run: npm --prefix questionservice test -- --coverage
    - run: npm --prefix webapp test -- --coverage
    - run: npm --prefix webapp run test:e2e
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
